### ISSUE TITLE
[bug] Why wait until ready not working

### ISSUE THREAD

**Issue by herlangga72** [zentered/cloudflare-preview-url#54]
**Describe the bug**
i dont know whats wrong with my config but it always trigger error

**To Reproduce**
Config file 
```
name: Main workflow
on:
  pull_request:
    branches:
      - master
      - main
    types: [opened, synchronize, reopened]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 60
    - name: Cloudflare Preview URL
      uses: zentered/cloudflare-preview-url@v1.4.0
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      with:
        cloudflare_project_id: ums-rps-fe
        wait_until_ready: true
    - name: Get URL
      run: echo "https://${{ steps.cloudflare_preview_url.outputs.preview_url }}"
 ```
 then the result like this
 
 
![image](https://github.com/zentered/cloudflare-preview-url/assets/44990885/bee0c905-7e70-4015-8dcf-17602c5da855)

![image](https://github.com/zentered/cloudflare-preview-url/assets/44990885/7da45af7-cfa2-49ce-aecb-724fbe85c1b5)

**Additional context**
Below what is happen in cloudflare pages
![image](https://github.com/zentered/cloudflare-preview-url/assets/44990885/f2adf666-f28d-4177-8935-b5afd43e4423)
