### ISSUE TITLE
Update documentation to reflect the usage of the account email

### ISSUE THREAD

**Issue by luckylwk** [zentered/cloudflare-preview-url#56]
It wasn't clear to us when using this that the API Token would not be used as a Bearer token when also providing the email address. Removing the email address immediately resolved the issue.

https://github.com/zentered/cloudflare-preview-url/blob/f5a8ce500de673fecdadb34533c2892830a07678/cloudflare.js#L22-L29

**Comment by PatrickHeneise** [comment]
Thanks for the feedback. It's been a while, but I think that depends on what account type you have? For my own website I use:

```
- name: cloudflare-preview-url
  uses: zentered/cloudflare-preview-url@v1.4.0
  id: cloudflare_preview_url
  env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  with:
    cloudflare_project_id: ''
    wait_until_ready: true
```

Which works fine; Is that a documentation issue or has something changed in Cloudflare API auth that I should be aware of?
